### ISSUE TITLE
浏览器支持哪些？

### ISSUE THREAD

**Issue by cheft** [livoras/simple-virtual-dom#1]
你好，看了你的博客和源码，受益匪浅。想问下你这个 simple-virtaul-dom 支持哪些浏览器， IE6+ 支持吗，[virtual-dom](https://github.com/Matt-Esch/virtual-dom) 我测试了一下是支持IE6+的。

**Comment by livoras** [comment]
@cheft 因为实现的时候为了方便使用了一些ES5的特性（如forEach），所以应该不支持IE6。但是这些不是必要的特性，所以后续会改写一下兼容IE6。

**Comment by cheft** [comment]
嗯，我尝试改了一下，IE8可以支持，IE6，7 有点问题，所以等你改好我再看看。最近自己也打算写个virtual dom 的东西，所以借鉴下你的。

**Comment by livoras** [comment]
@cheft 可以。也欢迎PR

**Comment by livoras** [comment]
增加IE5+支持 https://github.com/livoras/simple-virtual-dom/commit/58beeecf5e40067ffa3410f2bfbab6e458da08cd，如果有IE下的其它问题。欢迎再开issue

**Comment by cheft** [comment]
IE6+ 测试已支持，太棒了！
