### ISSUE TITLE
Improve compatibility with JSX

### ISSUE THREAD

**Issue by download13** [livoras/simple-virtual-dom#7]
At the moment el has the pattern `el(name, props, children)` but this means JSX doesn't work with it.

I've been needing to write a helper function that's basically just:
```
function h(name, props, ...children) {
    return el(name, props, children);
}
```

Is compatibility with JSX a concern for this library?

**Comment by livoras** [comment]
Thanks for this suggestion. It may be improved in future version. PR welcomes!

**Comment by download13** [comment]
Great! I'll push one up!

**Comment by download13** [comment]
Should be up as #10

**Comment by livoras** [comment]
closed, see https://github.com/livoras/simple-virtual-dom/pull/10
